apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicasCount | default  "1" }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailableCount }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.internalPort }}"
      labels:
        app: {{ .Chart.Name }}
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.http }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.ports.http }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.ports.http }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LOGLEVEL
              value: debug
            - name: ADDR
              value: $(POD_IP):{{ .Values.service.ports.http }}
            - name: CLUSTER_ENV
              value: {{ .Values.config.CLUSTER_ENV }}
            - name: DISPATCHER_ADDR
              value: {{ .Values.config.DISPATCHER_ADDR }}
            - name: GCE_API_KEY
              value: {{ .Values.config.GCE_API_KEY }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/autoscaler
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
