replicasCount: 1
maxUnavailableCount: 1

image:
  repository: gcr.io/videocoin-network/autoscaler
  tag: latest
  pullPolicy: Always

service:
  name: http
  type: NodePort
  externalPort: 80
  internalPort: 8013

resources: {}
config: {}
secrets: {}

prometheus:
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  pushgateway:
    enabled: false
  alertmanagerFiles:
    alertmanager.yml: |-
      global:
        # slack_api_url: ''

      receivers:
        - name: default-receiver
        - name: autoscaler
          webhook_configs:
            - url: http://autoscaler/prometheus/webhook

      route:
        receiver: default-receiver
        routes: 
          - receiver: autoscaler
            group_wait: 0s
            group_interval: 0s
            repeat_interval: 1m
            match_re:
              alertname: NeedMoreTranscoders|NeedLessTranscoders
  serverFiles:
    alerts: ""
    rules: ""
    prometheus.yml: |-
      global:
        scrape_interval: 5s
        evaluation_interval: 10s

      rule_files:
        - /etc/config/rules
        - /etc/config/alerts

      scrape_configs:
        - job_name: dispatcher
          static_configs:
            - targets:
              - dispatcher:15008
        - job_name: autoscaler
          static_configs:
            - targets:
              - autoscaler:80
