replicasCount: 1
maxUnavailableCount: 1

image:
  repository: registry.videocoin.net/cloud/autoscaler
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

service:
  ports:
    http: 8013

serviceAccount:
  name: default

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 10m
   memory: 16Mi

config: {}

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-autoscaler"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/autoscaler/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/autoscaler/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
