replicasCount: 1
maxUnavailableCount: 1

image:
  repository: registry.videocoin.net/cloud/autoscaler
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

service:
  name: http
  type: NodePort
  ports:
    http: 8013

serviceAccount:
  name: default

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 200m
   memory: 256Mi

config:
  CLUSTER_ENV: dev
  DISPATCHER_ADDR: d.dev.videocoin.net:5008
  GCE_API_KEY: "AIzaSyAIzJbgOs8VnaJRRJpOPxSMePoTsX_mL5g"

prometheus:
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  pushgateway:
    enabled: false
  alertmanagerFiles:
    alertmanager.yml: |-
      global:
        # slack_api_url: ''

      receivers:
        - name: default-receiver
        - name: autoscaler
          webhook_configs:
            - url: http://autoscaler.console.svc.cluster.local:8013/prometheus/webhook

      route:
        receiver: default-receiver
        routes: 
          - receiver: autoscaler
            group_wait: 0s
            group_interval: 0s
            repeat_interval: 1m
            match_re:
              alertname: NeedMoreTranscoders|NeedMorePreemtibleTranscoders|NeedLessTranscoders
  serverFiles:
    alerts: |-
      ALERT NeedMoreTranscoders
        IF clamp_max(sum(dispatcher_tasks_total{status="PENDING",type="LIVE"}) WITHOUT (instance, job, status, type) - sum(autoscaler_instances{status="creating"}) WITHOUT (instance, job, status), 3) > 0
        ANNOTATIONS {
            summary = "Need to create {{ $value }} transcoders",
            count = "{{ $value }}"
        }

      ALERT NeedMorePreemtibleTranscoders
        IF clamp_max(sum(dispatcher_tasks_total{status="PENDING",type="VOD"}) WITHOUT (instance, job, status, type) - sum(autoscaler_instances{status="creating"}) WITHOUT (instance, job, status), 3) > 0
        ANNOTATIONS {
            summary = "Need to create preemtible {{ $value }} transcoders",
            count = "{{ $value }}"
        }

      ALERT NeedLessTranscoders
        IF avg_over_time(miners_internal_miner_status{status="IDLE"}[30s]) == 1
        FOR 300s
        ANNOTATIONS {
            summary = "Need to delete {{ $value }} transcoders",
            count = "{{ $value }}"
        }
    rules: ""
    prometheus.yml: |-
      global:
        scrape_interval: 5s
        evaluation_interval: 10s

      rule_files:
        - /etc/config/rules
        - /etc/config/alerts

      scrape_configs:
        - job_name: dispatcher
          static_configs:
            - targets:
              - dispatcher:15008
        - job_name: autoscaler
          static_configs:
            - targets:
              - autoscaler:8013
        - job_name: miners
          static_configs:
            - targets:
              - miners:15011

annotations: {}
